/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sociaal.drools.shopping;

dialect "mvel"

import jade.lang.acl.ACLMessage;
import jade.domain.introspection.Event;

rule "Notificacion ganador"
    salience 100
    when
        $c1 : ACLMessage(content.startsWith("sd1"))
        $c2 : ACLMessage($c1.sender == sender,
        		content.startsWith("sd2"), 
        		postTimeStamp>$c1.postTimeStamp)
    then        
        System.out.println( "Recibido mensaje"); 
        System.out.println( "Recibido mensaje "+$c1.postTimeStamp+ " :" +$c2.postTimeStamp);
end
